language: go

env:
  global:
    - GO111MODULE="on"
    - GOPROXY="https://proxy.golang.org"

matrix:
  include:
    - os: linux
      go: 1.12.x
      env: MAIN_ENV=1
    - os: osx
      go: 1.12.x
    - os: windows
      go: 1.12.x

install: true

script:
  - go install ./...
  - go test ./...
  - if [[ $TRAVIS_OS_NAME != windows ]]; then go test -short -race ./...; fi
  - if [[ -n $MAIN_ENV ]]; then diff <(echo -n) <(gofmt -d .); fi
  - if [[ -n $MAIN_ENV ]]; then cd _fuzz/it && ./fuzz-ci local-regression 2>&1 | grep -vE '^Running|^Executed'; fi
  - if [[ -n $MAIN_ENV && $TRAVIS_EVENT_TYPE == push && $TRAVIS_BRANCH == master ]]; then ./fuzz-ci fuzzing; fi
