language: go

matrix:
  include:
    - os: linux
      go: "1.10"
    - os: linux
      go: 1.10.x
    - os: linux
      go: 1.11.x
    - os: osx
      go: 1.11.x

go_import_path: mvdan.cc/sh

install: true

script:
  - go get -d -t ./...
  - go install ./...
  - go test ./...
  - go test -short -race ./...
  - shfmt -version
