language: go

env:
  global:
    - GO111MODULE=on

matrix:
  include:
    - os: linux
      go: 1.11.x
    - os: linux
      go: 1.12.x
      env: LATEST_GO=1
    - os: osx
      go: 1.12.x
    - os: windows
      go: 1.12.x

install: true

script:
  - go install ./...
  - go test ./...
    # TODO: reenable test -race on windows once TestInteractive stops failing
  - if [[ $TRAVIS_OS_NAME != "windows" ]]; then go test -short -race ./...; fi
  - shfmt -version
  - if [[ -n $LATEST_GO ]]; then diff <(echo -n) <(gofmt -d .); fi
