on: [push, pull_request]

name: Go
jobs:

  test:
    strategy:
      matrix:
        # TODO: use .x once the setup-go action doesn't run into unauthenticated
        # rate limites. See: https://github.com/actions/setup-go/issues/16
        go-version: [1.11.9, 1.12.9]
        # TODO: reenable windows once this issue is fixed:
        # https://github.community/t5/GitHub-Actions/TEMP-is-broken-on-Windows/m-p/30432
        # platform: [ubuntu-latest, macos-latest, windows-latest]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Download Go dependencies
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go mod download
    - name: Test
      run: go test -count=1 ./...
    - name: Test with -short -race
      run: go test -short -race -count=1 ./...
